# frozen_string_literal: true
# Generated by scripts/render-homebrew-tap-formula.sh — do not edit shas by hand.

class KaizenCli < Formula
  desc "Distributable agent observability: sessions, retros, and repo-level improvement for coding agents"
  homepage "https://github.com/marquesds/kaizen"
  version "0.1.27"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.27/kaizen-v0.1.27-aarch64-apple-darwin.tar.gz"
      sha256 "6828f1279397a5a5f5ed3e54d8755e07341e8398898338ded044797fdde13e9c"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.27/kaizen-v0.1.27-x86_64-apple-darwin.tar.gz"
      sha256 "4247c76f8e0d4e0ca8cbb47669437b9bb38bc430603c95e8e2b2a6b24fe50d3f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.27/kaizen-v0.1.27-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1b5b2d6fcf4eac5710f76aade14c8afd9caf561a660165fd83fc83fbfd2489c0"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.27/kaizen-v0.1.27-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8117ce278cfbf377dd90fa03887ba87b8808c6ec4bf0152f9a1de3f79efc21f1"
    end
  end

  def install
    bin.install Dir.glob("kaizen-*/kaizen").first
  end

  test do
    system bin/"kaizen", "--version"
  end
end
