# frozen_string_literal: true
# Generated by scripts/render-homebrew-tap-formula.sh — do not edit shas by hand.

class KaizenCli < Formula
  desc "Distributable agent observability: sessions, retros, and repo-level improvement for coding agents"
  homepage "https://github.com/marquesds/kaizen"
  version "0.1.35"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.35/kaizen-v0.1.35-aarch64-apple-darwin.tar.gz"
      sha256 "af39a466047f6f81c91a71994a2ce91836c7911bc0a711a7ea0b5b137b058698"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.35/kaizen-v0.1.35-x86_64-apple-darwin.tar.gz"
      sha256 "796ae7187a4303461b7d01eb5235e0349346a5037b78e5eeb0e5a5a2a199c17b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.35/kaizen-v0.1.35-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "37131c25083c7171e7a4adc5c413fb0720c5e8c97915e907bcbd54ad09262ea3"
    end
    on_intel do
      url "https://github.com/marquesds/kaizen/releases/download/v0.1.35/kaizen-v0.1.35-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bd065f798c88286c83b8e9699d4c243823b82b1f5802ec54a03833ab6994ce97"
    end
  end

  def install
    bin.install Dir.glob("kaizen-*/kaizen").first
  end

  test do
    system bin/"kaizen", "--version"
  end
end
